import { createClient } from "npm:@supabase/supabase-js@2"
import { getCorsHeaders, handleOptions, jsonResponse, errorResponse } from "../_shared/cors.ts"

const MAX_BATCH_SIZE = 50
const MAX_MESSAGE_LENGTH = 2000
const MAX_STACK_LENGTH = 10000
const DEDUP_WINDOW_HOURS = 24
const GITHUB_API_BASE = "https://api.github.com"
const GITHUB_OWNER = "bradley-t-t"

const PROJECT_TO_GITHUB_REPO: Record<string, string> = {
    "smyrnatools.com": "smyrnatools-com",
    "baytowngocarts.com": "baytowngocarts-com",
    "book-writer": "book-writer",
    "coreminecraft.com": "coreminecraft-com",
    "taylorurl.com": "taylorurl-com",
    "setxfootball.com": "setxfootball-com",
    "kildred.com": "kildred-com",
    "charliets.com": "charliets",
}

interface ErrorReport {
    project: string
    error_message: string
    stack_trace?: string
    source_file?: string
    line_number?: number
    column_number?: number
    component_stack?: string
    url: string
    user_agent?: string
    browser?: string
    os?: string
}

function getAdminClient() {
    return createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SERVICE_ROLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY")!,
    )
}

function truncate(value: string | undefined | null, maxLength: number): string | null {
    if (!value || typeof value !== "string") return null
    return value.slice(0, maxLength)
}

async function computeErrorHash(project: string, message: string, file: string | null, line: number | null): Promise<string> {
    const raw = `${project}|${message}|${file ?? ""}|${line ?? ""}`
    const encoded = new TextEncoder().encode(raw)
    const hashBuffer = await crypto.subtle.digest("SHA-256", encoded)
    return Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, "0")).join("")
}

function validateErrorReport(entry: unknown): ErrorReport | null {
    if (!entry || typeof entry !== "object") return null
    const record = entry as Record<string, unknown>

    const project = typeof record.project === "string" ? record.project.trim() : ""
    const errorMessage = typeof record.error_message === "string" ? record.error_message.trim() : ""
    const url = typeof record.url === "string" ? record.url.trim() : ""

    if (!project || !errorMessage || !url) return null

    return {
        project,
        error_message: truncate(errorMessage, MAX_MESSAGE_LENGTH)!,
        stack_trace: truncate(record.stack_trace as string, MAX_STACK_LENGTH),
        source_file: truncate(record.source_file as string, MAX_MESSAGE_LENGTH),
        line_number: typeof record.line_number === "number" ? record.line_number : null,
        column_number: typeof record.column_number === "number" ? record.column_number : null,
        component_stack: truncate(record.component_stack as string, MAX_STACK_LENGTH),
        url: truncate(url, MAX_MESSAGE_LENGTH)!,
        user_agent: truncate(record.user_agent as string, MAX_MESSAGE_LENGTH),
        browser: truncate(record.browser as string, 100),
        os: truncate(record.os as string, 100),
    } as ErrorReport
}

function buildIssueBody(report: ErrorReport, errorHash: string): string {
    const sections = [
        `**Project:** ${report.project}`,
        `**Page:** ${report.url}`,
        `**Browser:** ${report.browser ?? "Unknown"} / ${report.os ?? "Unknown"}`,
        "",
        "## Error",
        "```",
        report.error_message,
        "```",
    ]

    if (report.source_file) {
        sections.push("", `**Source:** \`${report.source_file}\`${report.line_number ? `:${report.line_number}` : ""}`)
    }

    if (report.stack_trace) {
        sections.push("", "## Stack Trace", "```", report.stack_trace.slice(0, 3000), "```")
    }

    if (report.component_stack) {
        sections.push("", "## Component Stack", "```", report.component_stack.slice(0, 2000), "```")
    }

    sections.push("", "---", `Error hash: \`${errorHash}\``, "*Auto-generated by error-reporting-service*")

    return sections.join("\n")
}

async function createGithubIssue(report: ErrorReport, errorHash: string): Promise<{ issueNumber: number, issueUrl: string, repo: string } | null> {
    const githubToken = Deno.env.get("GITHUB_TOKEN")
    if (!githubToken) return null

    const repo = PROJECT_TO_GITHUB_REPO[report.project]
    if (!repo) return null

    const title = `Client Error: ${report.error_message.slice(0, 120)}`
    const body = buildIssueBody(report, errorHash)

    try {
        const response = await fetch(`${GITHUB_API_BASE}/repos/${GITHUB_OWNER}/${repo}/issues`, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${githubToken}`,
                "Accept": "application/vnd.github+json",
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                title,
                body,
                labels: ["bug", "client-error"],
            }),
        })

        if (!response.ok) return null

        const issue = await response.json()
        return { issueNumber: issue.number, issueUrl: issue.html_url, repo: `${GITHUB_OWNER}/${repo}` }
    } catch {
        return null
    }
}

async function upsertError(supabase: ReturnType<typeof createClient>, report: ErrorReport, errorHash: string) {
    const dedupCutoff = new Date(Date.now() - DEDUP_WINDOW_HOURS * 60 * 60 * 1000).toISOString()

    const { data: existing } = await supabase
        .from("client_errors")
        .select("id, error_count")
        .eq("error_hash", errorHash)
        .eq("fixed", false)
        .gte("created_at", dedupCutoff)
        .limit(1)
        .single()

    if (existing) {
        await supabase
            .from("client_errors")
            .update({ error_count: existing.error_count + 1, updated_at: new Date().toISOString() })
            .eq("id", existing.id)
        return "incremented"
    }

    const githubIssue = await createGithubIssue(report, errorHash)

    const { error } = await supabase.from("client_errors").insert({
        ...report,
        error_hash: errorHash,
        github_issue_number: githubIssue?.issueNumber ?? null,
        github_issue_url: githubIssue?.issueUrl ?? null,
        github_repo: githubIssue?.repo ?? null,
    })

    if (error) throw error
    return "inserted"
}

Deno.serve(async (req) => {
    const origin = req.headers.get("origin")
    if (req.method === "OPTIONS") return handleOptions(origin)

    const headers = getCorsHeaders(origin)
    const url = new URL(req.url)
    const endpoint = url.pathname.split("/").pop()

    if (req.method !== "POST") {
        return errorResponse("Method not allowed", headers, 405)
    }

    if (endpoint !== "report-batch") {
        return errorResponse("Invalid endpoint", headers, 404)
    }

    const body = await req.json().catch(() => null)
    if (!body || !Array.isArray(body.errors) || body.errors.length === 0) {
        return errorResponse("Request body must contain a non-empty 'errors' array", headers)
    }

    if (body.errors.length > MAX_BATCH_SIZE) {
        return errorResponse(`Batch size exceeds maximum of ${MAX_BATCH_SIZE}`, headers)
    }

    const supabase = getAdminClient()
    let insertedCount = 0
    let incrementedCount = 0
    let invalidCount = 0

    for (const entry of body.errors) {
        const report = validateErrorReport(entry)
        if (!report) {
            invalidCount++
            continue
        }

        try {
            const errorHash = await computeErrorHash(report.project, report.error_message, report.source_file ?? null, report.line_number ?? null)
            const result = await upsertError(supabase, report, errorHash)
            if (result === "inserted") insertedCount++
            else incrementedCount++
        } catch {
            invalidCount++
        }
    }

    return jsonResponse({ inserted: insertedCount, incremented: incrementedCount, invalid: invalidCount }, headers)
})
