export const SLASH_COMMANDS = [
  {
    command: '/tasks',
    label: 'Tasks',
    description: 'List pending tasks',
    icon: 'CheckSquare',
    fillText: "What's pending today?",
  },
  {
    command: '/newtask',
    label: 'New Task',
    description: 'Add a new task',
    icon: 'Plus',
    fillText: 'Add a task: ',
  },
  {
    command: '/projects',
    label: 'Projects',
    description: 'List active projects',
    icon: 'FolderOpen',
    fillText: 'List my active projects.',
  },
  {
    command: '/devices',
    label: 'Devices',
    description: 'Smart home devices',
    icon: 'Wifi',
    fillText: 'List my smart home devices.',
  },
  {
    command: '/memory',
    label: 'Memory',
    description: 'Search your memory',
    icon: 'Brain',
    fillText: 'Search your memory for ',
  },
  {
    command: '/code',
    label: 'Code',
    description: 'Dispatch coding work',
    icon: 'Code',
    fillText: 'Dispatch a coding task to ',
  },
  {
    command: '/repos',
    label: 'Repos',
    description: 'List GitHub repos',
    icon: 'GitBranch',
    fillText: 'List my GitHub repos.',
  },
  {
    command: '/search',
    label: 'Search',
    description: 'Search the web',
    icon: 'Search',
    fillText: 'Search the web for ',
  },
  {
    command: '/remind',
    label: 'Remind',
    description: 'Set a reminder',
    icon: 'Bell',
    fillText: 'Remind me to ',
  },
  {
    command: '/home',
    label: 'Home',
    description: 'Control smart home',
    icon: 'Home',
    fillText: 'Turn on ',
  },
]
